### ISSUE TITLE
Allow for a custom user-agent string in configuration block.

### ISSUE THREAD

**Issue by djhopper01** [paulspringett/bcx#4]
37signals recommends you pass a user-agent string identifying your app. Right now, the user-agent string is simply `Faraday v0.8.7`.

The way I've seen this done in the [google ruby client](https://github.com/google/google-api-ruby-client) is the following:
- They let you set your application name and version.
- The user-agent is set to this: `{app_name} google-api-ruby-client/{version} {os_name}/{os_version}`

I know this isn't a big deal right now, but it's something to keep in mind since 37signals recommends it.

**Comment by paulspringett** [comment]
Closed by #12
